// Copyright Contributors to the Open Cluster Management project

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// StrategyListerExpansion allows custom methods to be added to
// StrategyLister.
type StrategyListerExpansion interface{}

// StrategyNamespaceListerExpansion allows custom methods to be added to
// StrategyNamespaceLister.
type StrategyNamespaceListerExpansion interface{}
